# This express Current Sensor data
Header header
float64 water_temperature #[degrees Celsius]
float64 compass_a #value of compassA, inner variable
float64 compass_b #value of compassB, inner variable
float64 x_velocity #X_axis[cm/sec]
float64 y_velocity #Y_axis[cm/sec]
float64 current_velocity #synthetic velocity[cm/sec]
float64 currentmeter_direction #sensor's direction[deg]
float64 current_direction #[deg]
float64 north_velocity #[cm/sec]
float64 east_velocity #[cm/sec]
float64 voltage #[V] 12V-24V
